# Generated by Django 3.0.2 on 2020-02-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=112, unique=True, verbose_name='code')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('keyword', models.CharField(max_length=255, verbose_name='关键字')),
            ],
            options={
                'verbose_name': '域名品牌',
                'verbose_name_plural': '域名品牌',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CDN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='CDN厂商')),
                ('code', models.CharField(max_length=112, unique=True, verbose_name='CDN英文')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'CDN厂商',
                'verbose_name_plural': 'CDN厂商',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='xxljob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('task_id', models.CharField(blank=True, max_length=3, verbose_name='task_id')),
                ('status', models.BooleanField(default=False, verbose_name='启动状态')),
                ('group', models.CharField(choices=[('boceNode', '拨测节点'), ('boceCenter', '拨测管理机')], default='boceNode', max_length=20, verbose_name='执行器')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='名称')),
                ('router', models.CharField(choices=[(0, 'frist'), (1, 'end'), (2, 'polling'), (3, 'random'), (4, 'balancing')], default='frist', max_length=10, verbose_name='路由策略')),
                ('jobCron', models.CharField(max_length=20, verbose_name='cron表达式')),
                ('type', models.CharField(choices=[(0, 'java'), (1, 'shell'), (2, 'python'), (3, 'php'), (4, 'nodejs')], default='python', max_length=10, verbose_name='GLUE类型')),
                ('block', models.CharField(choices=[(0, 'signle'), (1, 'discard'), (2, 'cover')], default='signle', max_length=10, verbose_name='阻塞策略')),
                ('author', models.CharField(max_length=12, verbose_name='负责人')),
                ('param', models.CharField(blank=True, max_length=30, verbose_name='任务参数')),
                ('code', models.TextField(blank=True, verbose_name='GLUE源代码')),
            ],
            options={
                'verbose_name': '拨测任务',
                'verbose_name_plural': '拨测任务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('ip', models.CharField(max_length=255, unique=True, verbose_name='IP')),
                ('cdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.CDN', verbose_name='CDN厂商')),
            ],
            options={
                'verbose_name': '边缘节点IP',
                'verbose_name_plural': '边缘节点IP',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('domain', models.CharField(max_length=255, verbose_name='域名')),
                ('type', models.CharField(choices=[('web', 'pc端'), ('h5', '移动端'), ('appdown', 'app下载'), ('agent', '代理')], default='web', max_length=10, verbose_name='类型')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '域名管理',
                'verbose_name_plural': '域名管理',
                'ordering': ['-create_time'],
            },
        ),
    ]
