# Generated by Django 3.0.2 on 2020-02-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxljob',
            name='dbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Brand', verbose_name='域名品牌'),
        ),
        migrations.AddField(
            model_name='xxljob',
            name='dtype',
            field=models.CharField(choices=[('web', 'pc端'), ('h5', '移动端'), ('appdown', 'app下载'), ('agent', '代理')], default='web', max_length=20, verbose_name='域名类型'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='block',
            field=models.CharField(choices=[('SERIAL_EXECUTION', '单机串行'), ('DISCARD_LATER', '丢弃后续调度'), ('COVER_EARLY', '覆盖之前调度')], default='signle', max_length=20, verbose_name='阻塞策略'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='group',
            field=models.CharField(choices=[('1', '拨测节点'), ('2', '拨测管理机')], default='boceNode', max_length=20, verbose_name='执行器'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='router',
            field=models.CharField(choices=[('FIRST', '第一个'), ('LAST', '最后一个'), ('ROUND', '轮询'), ('RANDOM', '随机'), ('SHARDING_BROADCAST', '分片广播')], default='frist', max_length=20, verbose_name='路由策略'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='type',
            field=models.CharField(choices=[('GLUE_GROOVY', 'java'), ('GLUE_SHELL', 'shell'), ('GLUE_PYTHON', 'python'), ('GLUE_PHP', 'php'), ('GLUE_NODEJS', 'nodejs')], default='python', max_length=20, verbose_name='GLUE类型'),
        ),
    ]
