# Generated by Django 3.0.2 on 2020-02-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20200223_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoceNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('ip', models.CharField(max_length=112, unique=True, verbose_name='ip')),
                ('endpoint_id', models.CharField(blank=True, max_length=112, null=True, verbose_name='endpoint_id')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '拨测节点',
                'verbose_name_plural': '拨测节点',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(choices=[('web', 'pc端'), ('h5', '移动端'), ('appdown', 'app下载'), ('agent', '代理'), ('other', '其他')], default='web', max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='dtype',
            field=models.CharField(choices=[('web', 'pc端'), ('h5', '移动端'), ('appdown', 'app下载'), ('agent', '代理'), ('other', '其他')], default='web', max_length=20, verbose_name='域名类型'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='group',
            field=models.CharField(choices=[('1', '拨测节点')], default='boceNode', max_length=20, verbose_name='执行器'),
        ),
    ]
