# Generated by Django 3.0.2 on 2020-02-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20200228_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocenode',
            name='location',
            field=models.CharField(default=1, max_length=112, verbose_name='location'),
            preserve_default=False,
        ),
    ]
