# Generated by Django 3.0.2 on 2020-03-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_bocenode_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain',
            new_name='name',
        ),
    ]
