# Generated by Django 3.0.2 on 2020-03-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20200302_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoceNodeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('AppName', models.CharField(max_length=255, unique=True, verbose_name='AppName名称')),
                ('sequence', models.SmallIntegerField(default=0, verbose_name='排序值')),
                ('gid', models.CharField(max_length=2, unique=True, verbose_name='group_id')),
            ],
            options={
                'verbose_name': '执行器分组',
                'verbose_name_plural': '执行器分组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='bocenode',
            name='group',
            field=models.ManyToManyField(blank=True, to='domains.BoceNodeGroup', verbose_name='执行器分组'),
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.BoceNodeGroup', verbose_name='执行器分组'),
        ),
    ]
