# Generated by Django 3.0.2 on 2020-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20200307_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bocenode',
            name='group',
        ),
        migrations.AddField(
            model_name='bocenodegroup',
            name='nodes',
            field=models.TextField(blank=True, verbose_name='节点列表'),
        ),
    ]
