# Generated by Django 3.0.2 on 2020-03-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_auto_20200308_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bocenodegroup',
            options={'ordering': ['sequence'], 'verbose_name': '执行器分组', 'verbose_name_plural': '执行器分组'},
        ),
        migrations.RemoveField(
            model_name='xxljob',
            name='dtype',
        ),
    ]
