# Generated by Django 3.0.2 on 2020-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_auto_20200308_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xxljob',
            name='dbrand',
        ),
        migrations.AddField(
            model_name='xxljob',
            name='dbrand',
            field=models.ManyToManyField(blank=True, to='domains.Brand', verbose_name='域名品牌'),
        ),
    ]
