# Generated by Django 3.0.2 on 2020-03-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_auto_20200308_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=112, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': '域名类型',
                'verbose_name_plural': '域名类型',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='bocenodegroup',
            options={'ordering': ['sequence'], 'verbose_name': '执行器', 'verbose_name_plural': '执行器'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.DomainType', verbose_name='类型'),
        ),
    ]
