# Generated by Django 3.0.2 on 2020-03-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_auto_20200313_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xxljob',
            name='dbrand',
        ),
    ]
