# Generated by Django 3.0.2 on 2020-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0013_remove_xxljob_dbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippool',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
    ]
