# Generated by Django 2.1.4 on 2020-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0014_auto_20200315_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippool',
            name='ip',
            field=models.CharField(max_length=112, unique=True, verbose_name='ip地址'),
        ),
    ]
