# Generated by Django 2.1.4 on 2020-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0015_auto_20200414_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bocenodegroup',
            name='nodes',
        ),
        migrations.AlterField(
            model_name='xxljob',
            name='group',
            field=models.CharField(blank=True, default=1, max_length=3, verbose_name='执行器'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoceNode',
        ),
        migrations.DeleteModel(
            name='BoceNodeGroup',
        ),
    ]
