# Generated by Django 2.1.4 on 2020-04-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0016_auto_20200416_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
