# Generated by Django 2.1.4 on 2020-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='名称')),
                ('host', models.CharField(max_length=112, verbose_name='主机')),
                ('user', models.CharField(max_length=112, verbose_name='账号')),
                ('password', models.CharField(max_length=112, verbose_name='密码')),
            ],
            options={
                'verbose_name': '邮件机器人',
                'verbose_name_plural': '邮件机器人',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='名称')),
                ('user', models.CharField(max_length=112, verbose_name='账号')),
                ('token', models.CharField(max_length=112, verbose_name='token')),
                ('chatid', models.CharField(max_length=112, verbose_name='账号')),
            ],
            options={
                'verbose_name': 'tg机器人',
                'verbose_name_plural': 'tg机器人',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ToUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='名称')),
                ('account', models.CharField(max_length=112, unique=True, verbose_name='账号')),
                ('type', models.CharField(choices=[('mail', 'mail'), ('telegram', 'telegram'), ('sms', 'sms')], default='mail', max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '接收方',
                'verbose_name_plural': '接收方',
                'ordering': ['-create_time'],
            },
        ),
    ]
