# Generated by Django 2.1.4 on 2020-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='chatid',
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='chat_id',
            field=models.CharField(default=1, max_length=112, verbose_name='chat_id'),
            preserve_default=False,
        ),
    ]
