# Generated by Django 2.1.4 on 2020-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20200418_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='user',
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='uid',
            field=models.CharField(default=1, max_length=112, verbose_name='账号id'),
            preserve_default=False,
        ),
    ]
