# Generated by Django 2.1.4 on 2020-04-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20200418_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToUser',
        ),
    ]
